### ISSUE TITLE
Minor typo in docstring for `query.IndexQuery.__init__()`

### ISSUE THREAD

**Issue by eprigorodov** [zopefoundation/Products.ZCatalog#24]
Docstring for `query.IndexQuery.__init__()` describes a `query` parameter whereas its current name is `request`. Github history does not contain renaming point.

**Comment by hannosch** [comment]
This code was factored out from another part of the codebase, where the first argument used to be and is still called request. In some ancient times that argument could actually be a HTTP request object, but that's not true anymore for quite a while.

Since the `__init__` method uses a local variable named `query` later on, it's probably easiest to change the docstring.
