### ISSUE TITLE
Replacement for CatalogAware?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.ZCatalog#26]
[Products.ZCatalog.CatalogPathAwareness.CatalogAware](https://github.com/zopefoundation/Products.ZCatalog/blob/3.2.x/src/Products/ZCatalog/CatalogPathAwareness.py) warned for a long time that it will be gone in Version 4.0.

The warning said that that the `CatalogAware` mix-in class should be replaced by event handlers.

Are there any pre-defined event handlers which could be easily used or is it up to the user of `Products.ZCatalog` to write them?

**Comment by tseaver** [comment]
How / when to {,re,un}index content is an application-specific concern, which is why the `CatalogAware` bits were pulled out.

CMFCore has a [`subscribers` module](https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/subscribers.py) which supplies those policies for CMF-based applications.

**Comment by hannosch** [comment]
As Tres said, it's up to the application to provide those event handlers. The CatalogAware and CatalogPathAware mixin classes weren't used in ZCatalog, CMF or Plone. So I deprecated them a while ago. All these manageAfterAdd methods were deprecated long before that when we got object lifecycle event handlers. I really wanted to get rid of the "five:deprecatedManageAddDelete" ZCML bits as well.

**Comment by icemac** [comment]
@tseaver Thank you for the pointer.
@hannosch Thank you for the clarification and +1 for getting rid of `five:deprecatedManageAddDelete`
