### ISSUE TITLE
queryplan: valueindexes have high cost on very large sites 

### ISSUE THREAD

**Issue by tdesvenain** [zopefoundation/Products.ZCatalog#39]
I have a site with 270.000 contents.

On this site, first call of valueindexes method of queryplan takes dozens of seconds to execute, because of the large amount of some indexes, as UID, id, Title, sortable_title, etc.
By the way, all of those indexes are excluded by the test over MAX_DISTINCT_VALUES.

I'm not sure if this is the right approach, but i fixed this problem by setting a list of excluded indexes. 
cf. https://github.com/zopefoundation/Products.ZCatalog/commit/bc7f90a62d0c54a9e59683f3967dd56f7ac35ecc
what is your opinion about this ? where is is the right place to set this list ?
thanks

**Comment by andbag** [comment]
In my opinion, the hard coded exclude list is too focused on plone (?). What's about a generic solution? Maybe you can identify a heuristic threshold based on the relation between the number of unique values and the total number of indexed objects, e.g. at line 204

```
DISTINCT_THRESHOLD = 0.6
if len(index)/float(len(index.documentToKeyMap())) > DISTINCT_THRESHOLD:
   continue
```

**Comment by d-maurer** [comment]
The estimation of the index size (as measured by the number of indexed values) via enumeration is straight forward but in most cases over conservative. Indexes derived from `UnIndex` have an efficient `indexSize` method. They maintain the number of indexed values in a `Length` object which can be read with a single ZODB load.

> `n_obj = index.numObjects()`

Note that `numObjects` is quite expensive: it must load all buckets of the associated `_unindex`. This is costly for site with many indexed objects.

**Comment by andbag** [comment]
Thank you for the hint. In the first approximation,
> `n_obj = index.numObjects()`

could be replaced by
>`n_obj = len(self.catalog)`

to achieve the same objective. `len(self.catalog)` can be read also with a single ZODB load. What's your opinion?

**Comment by d-maurer** [comment]
Andreas Gabriel wrote at 2019-3-7 23:40 -0800:
>Thank you for the hint. In the first approximation,
>> `n_obj = index.numObjects()`
>
>could be replaced by
>>`n_obj = len(self.catalog)`
>
>to achieve the same objective. `len(self.catalog)` can be read also with a single ZODB load. What's your opinion?

Good!

**Comment by andbag** [comment]
It appears the problem is due to another issue and we don't need a sophisticated solution as described above.

`index.uniqueValues()`

a generator, but it doesn't use within the method an iterator for the loop. That's maybe the reason for the performance issue. 

https://github.com/zopefoundation/Products.ZCatalog/blob/dd30d4413eb1090f2a05bb4cfe438dc0a9690611/src/Products/PluginIndexes/unindex.py#L682-L683

It should use `self._index.iterkeys()` instead. I have made the necessary changes in the branch [fix_unindex_uniquevalues](https://github.com/zopefoundation/Products.ZCatalog/tree/fix_unindex_uniquevalues). If you agree with my assumption, I will create a PR.

**Comment by d-maurer** [comment]
Andreas Gabriel wrote at 2019-4-9 08:36 -0700:
>It appears the problem is due to another issue and we don't need a sophisticated solution as described above.

In `valueindexes` `uniqueValues` is only used to check that
the index has not too many values. In my view, it is far
more natural to use `indexSize` for this purpose.
This would give:
                if index.indexSize() < MAX_INDEX_VALUES:
instead of
                values = index.uniqueValues()
                i = 0
                for value in values:
                    # the total number of unique values might be large and
                    # expensive to load, so we only check if we can get
                    # more than MAX_DISTINCT_VALUES
                    if i >= MAX_DISTINCT_VALUES:
                        break
                    i += 1
                if i > 0 and i < MAX_DISTINCT_VALUES:
                    # Only consider indexes which actually return a number
                    # greater than zero


`indexSize` is a responsibility of `IPluggableIndex`: any
index should have this method.
`unindex.UnIndex`, the base class for most (all?) value indexes, has
an efficient implementation.


>`index.uniqueValues()`
>
>a generator, but it doesn't use within the method an iterator for the loop. That's maybe the reason for the performance issue.
>
>https://github.com/zopefoundation/Products.ZCatalog/blob/dd30d4413eb1090f2a05bb4cfe438dc0a9690611/src/Products/PluginIndexes/unindex.py#L682-L683
>
>It should use `self._index.iterkeys()` instead.

All indexes I know of use a BTrees variant as indexes.
Their "keys" method (and friends) does not return a list and has a good chance
to be efficient (when used for iteration).
If we can trust the Python implementation (--> "BTrees._base._Tree"),
then "t.iterkeys()" is essentially "iter(t.keys())".

Thus, I doubt that the use of "t.keys" (over "t.iterkeys") is
responsible for less than optimal performance of "valueindexes".

**Comment by andbag** [comment]
Ok, I didn't check the BTrees sources. Unfortunately, the method 'iterkeys' will not increase the performance. The code of `valueindexes` still contains a desired function extension that has not yet been implemented.

https://github.com/zopefoundation/Products.ZCatalog/blob/dd30d4413eb1090f2a05bb4cfe438dc0a9690611/src/Products/ZCatalog/plan.py#L194-L197

I have now implemented this mechanism using a chi-square test. Probably there are performance problems again despite the use of `indexSize`. For determining the distribution of the number of items per value the length of the `IITreeSet` objects has to be determined. The calculation is again based on the `uniqueValues` method.

https://github.com/zopefoundation/Products.ZCatalog/blob/800f45db5855877862daacc58d781cd6fe5e1f4b/src/Products/ZCatalog/plan.py#L229

BTW, I find it quite strange that all objects from the `BTrees` module do not have an efficient implementation for the `__len__` method.

**Comment by d-maurer** [comment]
Andreas Gabriel wrote at 2019-4-11 00:21 -0700:
> ...
 For determining the distribution of the number of items per value the length of the `IITreeSet` objects has to be determined.

This will be expensive: the objects of the "XXTreeXXX" family
do not store their length; determining the length means
iterating over all leaf nodes and summing up their length.
For persistent objects, this entails the load of almost all
nodes from the ZODB.

> ...
>BTW, I find it quite strange that all objects from the `BTrees` module do not have an efficient implementation for the `__len__` method.

Likely, this has to do with conflict resolution:
Object specific conflict resolution sees only a single object at a time --
it cannot examine other conflicting objects in the same transaction.
An XXTreeXXX object internally consists of (potentially) many
individually persistent subobjects. Its "length" would necessarily
be a "global" information, dependent on all those subobjects.
This would make local conflict resolution for a subobject impossible
(or at least drastically reduce its potential) because the local
resolution would also need to update the global "length" information.

**Comment by andbag** [comment]
Is there anything against having a `Length` object for each `IITreeSet` object? The same was done for the `__len__` method of the `UnIndex` class. Probably this will be a overkill for indexes with a lot of unique values, isn't it?

**Comment by d-maurer** [comment]
Andreas Gabriel wrote at 2019-4-11 04:53 -0700:
>Is there anything against having a `Length` object for each `IITreeSet` object? The same was done for the `__len__` method of the `UnIndex` class. Probably this will be a overkill for indexes with a lot of unique values, isn't it?

The size requirements will at most double and will typically be
negligable. Thus, I do not see a problem there.

However, even with an efficient length, you may need a long time
to compute your information -- typically because you have
lots of different keys. If you do your preliminary computations
only for indexes with few keys, then this may be acceptable.


There is an alternative possibility: when I remember right,
then all set operations do not produce tree structures but
flat ("bucket") structures. Those have an efficient "len".
This means that after the first intersection, you can measure efficiently the
size reduction by each followup intersection. However, I am not
sure whether this will give better plans as those determines based
on intersection time.


If you trust the self optimizing potential of the query plan,
you will not need a very sophisticated algorithm to determine
the initial plan -- as the plan becomes better with (almost) every search
and hopefully quickly reaches a good quality.


"dm.incrementalsearch" (this is an alternative to the `BTrees` set operations)
makes optimizations based on an estimated size. For a `BTree` it
determines the exact size of the root node (this is fast) and assumes that the
tree is completely homogenous and all non-root nodes are filled at
75 %. With these assumptions it can estimate the size by determining the
depth of the first (= left most) bucket (=leaf).
Maybe, similar estimations are sufficient for your computations.

**Comment by andbag** [comment]
You're right. I don't think it makes any sense to invest any more time in a better solution. The self-optimization of the query plan can correct initial misadjustments. Using the `indexSize` method solves the current issue.

BTW eight years ago, Hanno had already been looking for an efficient method for determining the length of `IITreeSet` ([Plone 4.1 - btree query improvements](http://plone.293351.n2.nabble.com/Plone-4-1-btree-query-improvements-td6638997.html)).

**Comment by andbag** [comment]
I've submitted a [PR](https://github.com/zopefoundation/Products.ZCatalog/pull/68) now, which should solve the performance problem, but without any sophisticated algorithm.
