### ISSUE TITLE
[ZMI] Styling of Tabs

### ISSUE THREAD

**Issue by sallner** [zopefoundation/Products.ZCatalog#45]
The management tabs should be adapted to the new ZMI interface. `manage_catalogView`, `manage_catalogIndexes` and `manage_catalogSchema` in particular would benefit from a redesign.

**Comment by azapletal** [comment]
Currently the ZMI `Select type to add ` is disabled when inside a ZCatalog. Latter is of folderish nature (`isPrincipiaFolderish=1`) – therefore it should be enabled.

**Comment by icemac** [comment]
See also zopefoundation/Zope#454.

**Comment by dataflake** [comment]
The tab styling is fixed in zopefoundation/Products.ZCatalog@3efa650d93999d7efc5c268d62df54534fd5be82 and the missing content add widget has been restored with zopefoundation/Zope@5b97a7aeab467cd71de1c08929a06d0320b9652c. I was surprised to see that the deciding factor in enabling or disabling that widget is the presence of a `manage_findForm` link (a "Find tab") in the object's tab bar.🙄
