### ISSUE TITLE
Strange decode function

### ISSUE THREAD

**Issue by ale-rt** [zopefoundation/Products.ZCatalog#58]
Looking at 
https://github.com/zopefoundation/Products.ZCatalog/blob/1ec5a94919994b2867776c09ba27b56d39c9d335/src/Products/ZCTextIndex/WidCode.py#L88-L96
it seems to me it might fail to produce the desired output in Python2 because decoding unicode will still return unicode and not a str as the code seems to require.

It seems to me that the proper fix is replacing the line:
```
if not isinstance(code, str): 
```
with:
```
if not six.PY2 and isinstance(code, six.binary_type)
```

Untested.

**Comment by d-maurer** [comment]
Alessandro Pisa wrote at 2019-3-8 06:53 -0800:
>Looking at
>https://github.com/zopefoundation/Products.ZCatalog/blob/1ec5a94919994b2867776c09ba27b56d39c9d335/src/Products/ZCTextIndex/WidCode.py#L88-L96
>it seems to me it might fail to produce the desired output in Python2 because decoding unicode will still return unicode and not a str as the code seems to require.

"decode" in Python 2 means "to unicde" (for a charset);
you must use "encode" in Python 2 to get `bytes` (aka "str").



--
Dieter

**Comment by ale-rt** [comment]
Well, the name of the function is decode... so I supposed the expected output is "text", unicode in py2 and str in py3.

**Comment by d-maurer** [comment]
Alessandro Pisa wrote at 2019-3-8 07:16 -0800:
>Well, the name of the function is decode... so I supposed the expected output is "text", unicode in py2 and str in py3.

With respect to charsets, this is true.

However, "decode" can also be used in other contexts,
e.g. "b64decode".

Regarding "widcodes", the meaning might in fact be different.
A "widcode" is a string coding a sequence of integers.
"widcode.decode" thus may mean: decode the string into its
sequence of integers.

The "encode" works as follows:
interpret each integer as a unicode codepoint -- this
gives a unicode string; the "widcode" is its "utf-8" encoding.

The "decode" works as follows:
"utf-8" decode the "widcode" giving a a unicode string
and transform it into the corresponding sequence of codepoint integers.

With the code you are citing, icemac wants to fix up a
bad Python 2 -> Python 3 ZODB conversion - which has mapped
the binary "widcode" to an "str".
Under Python 2, no such fix is necessary.

**Comment by icemac** [comment]
@davisagli You proposed #46, are you okay with the change @ale-rt suggested?

**Comment by davisagli** [comment]
I don't think the change is necessary. @d-maurer has it pretty much right. The WidCode encoding is not about text vs bytes but is about encoding (meaning serializing) a list of integers into a (native) string.

If it was encoded in Python 2 and is decoded in Python 2, then the decode function gets a (bytes) str. No transformation is necessary before converting str to integers, and the `if not isinstance(code, str):` condition fails so no transformation is done.

If it was encoded in Python 3 and is decoded in Python 3, then the decode function gets a (text) str. No transformation is necessary before converting str to integers, and the condition fails so no transformation is done.

If it was encoded in Python 2, then the database converted in a way that leaves bytestrings intact, then decoding in Python 3 will receive bytes where it needs a str. Then `if not isinstance(code, str):` succeeds and the bytes will be decoded as latin1. This is just a way to turn it into text leaving the bits intact, since the first 255 bytes of Unicode are the same as latin-1.

**Comment by davisagli** [comment]
That said, I think it will also work fine the way that @ale-rt proposed, and maybe it makes it easier to understand.
